name: Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  pages: write
  id-token: write

# List of jobs
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
      with:
          install_command: npm i --include=dev
          # build_command: npm run build-storybook # default: npm run build-storybook
          path: storybook-static # default: dist/storybook
          checkout: false # default: true
